### ISSUE TITLE
Webpage offline

### ISSUE THREAD

**Issue by lpettrich** [jessicawleigh/popart#7]
Hello!
I wanted to download the compiled version for windows but I noticed that the webpage http://popart.otago.ac.nz/ is offline. 
Is there another way to get the compiled version?
Thank you!
Best wishes
Laura

**Comment by rafaelvieira98** [comment]
Same problem here

**Comment by lpettrich** [comment]
I checked again and now the webpage is working again! Thank you for fixing it! 👍🏻
